#*** Spring Application Properties ***#
server:
  port: 8765
#*** Spring Cloud Gateway Routing to remove prefix service name from all API ***#
spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: User-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**,/user-groups/**
        - id: group-service
          uri: lb://attendance-service
          predicates:
            - Path=/attendance/**,/attendance-roles/**
        - id: role-service
          uri: lb://ROLE-SERVICE
          predicates:
            - Path=/roles/**
    discovery:
      enabled: true

eureka:
  instance:
    hostname: localhost
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/


#*** Spring Cloud Gateway Properties (Providing custom path) hence commented ***#
#spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true