#*** Spring Application Properties ***#
server:
  port: 8765

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: User-service
          uri: lb://User-service  # Ensure this matches the application name of your user service
          predicates:
            - Path=/users/**
        - id: Attendance-service
          uri: lb://attendance-service  # Ensure this matches the application name of your attendance service
          predicates:
            - Path=/attendance/**
        - id: Role-service
          uri: lb://role-service  # Ensure this matches the application name of your role service
          predicates:
            - Path=/roles-permissions/**
    discovery:
      enabled: true  # Enables discovery client integration

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive.function.client.WebClient: DEBUG

#*** Spring Cloud Gateway Properties (Providing custom path) hence commented ***#
#spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true